/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author PERSONAL
 */
public class adminpanelusuarioregistrar extends javax.swing.JPanel {

    /**
     * Creates new form adminpanelclienteregistrar
     */
    public adminpanelusuarioregistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTNadminregistrarusu = new javax.swing.JButton();
        TXTadminidusu = new javax.swing.JTextField();
        TXTadminusu = new javax.swing.JTextField();
        TXTadmincontra = new javax.swing.JTextField();
        TXTadminrango = new javax.swing.JTextField();
        TXTadminidemp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Registrar Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID Usuario: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Usuario: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Contraseña: ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Rango: ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ID Empleado: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        BTNadminregistrarusu.setBackground(new java.awt.Color(187, 142, 211));
        BTNadminregistrarusu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BTNadminregistrarusu.setText("Registrar");
        add(BTNadminregistrarusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 170, 40));

        TXTadminidusu.setBackground(new java.awt.Color(102, 102, 102));
        TXTadminidusu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminidusu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        add(TXTadminidusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 200, 30));

        TXTadminusu.setBackground(new java.awt.Color(102, 102, 102));
        TXTadminusu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminusu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        add(TXTadminusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 30));

        TXTadmincontra.setBackground(new java.awt.Color(102, 102, 102));
        TXTadmincontra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmincontra.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        add(TXTadmincontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 200, 30));

        TXTadminrango.setBackground(new java.awt.Color(102, 102, 102));
        TXTadminrango.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminrango.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        add(TXTadminrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 200, 30));

        TXTadminidemp.setBackground(new java.awt.Color(102, 102, 102));
        TXTadminidemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminidemp.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));
        add(TXTadminidemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 200, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNadminregistrarusu;
    private javax.swing.JTextField TXTadmincontra;
    private javax.swing.JTextField TXTadminidemp;
    private javax.swing.JTextField TXTadminidusu;
    private javax.swing.JTextField TXTadminrango;
    private javax.swing.JTextField TXTadminusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
