/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import DAO.*;
import Model.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PERSONAL
 */
public class admin_libros extends javax.swing.JPanel {
    DefaultTableModel m = new DefaultTableModel();
    private static final Logger logger = Logger.getLogger(LibroDAO.class.getName());

    /**
     * Creates new form admin_libros
     */
    public admin_libros() {
        initComponents();
        cabecera();
        
        TXTadminactulibidlib.addFocusListener(new FocusAdapter() {
    @Override
    public void focusLost(FocusEvent e) {
        String idlib= TXTadminactulibidlib.getText();
        LibroDAO libdao= new LibroDAO();
        
        if (!idlib.isEmpty()) {
            System.out.println("Hay algo en el txtfield p");
            try{
                Libro autolib= libdao.obtenerPorId(idlib);
                if (autolib != null) {//si es q el txtfield no esta vacio y el libro existe
                    TXTadminactulibtitu.setText(autolib.getTitulo());
                    TXTadminactulibpre.setText(String.valueOf(autolib.getPrecio()));
                    TXTadminactulibidaut.setText(autolib.getIdAutor());
                    TXTadminactulibidedit.setText(autolib.getIdEdito());
                    TXTadminactulibidgen.setText(autolib.getIdGen());
                    TXTadminactulibididio.setText(autolib.getIdIdioma());   
                    System.out.println("Libro encontrado");
                }else{
                    JOptionPane.showMessageDialog(null, "Libro no Existe o no Encontrado", "TY Beyonce", JOptionPane.INFORMATION_MESSAGE);
                }
                
           }catch(SQLException intentalo){//problemas con la base de datos
                JOptionPane.showMessageDialog(null, "Error al buscar el Libro" + intentalo.getMessage(), "Fue", JOptionPane.ERROR_MESSAGE); 
                intentalo.printStackTrace(); 
                
            }
            
        }
      
    }
});
    }
    
    public void cabecera(){
        m.addColumn("ID_LIBRO");
        m.addColumn("TÍTULO");
        m.addColumn("PRECIO");
        m.addColumn("ID_AUTOR");
        m.addColumn("ID_EDITORIAL");
        m.addColumn("ID_GÉNERO");
        m.addColumn("ID_IDIOMA");
        
        TBadminbuscarlib.setModel(m);
        
        TBadminbuscarlib.getColumnModel().getColumn(0).setPreferredWidth(75);
        TBadminbuscarlib.getColumnModel().getColumn(1).setPreferredWidth(150);
        TBadminbuscarlib.getColumnModel().getColumn(2).setPreferredWidth(80);
        TBadminbuscarlib.getColumnModel().getColumn(3).setPreferredWidth(80);
        TBadminbuscarlib.getColumnModel().getColumn(4).setPreferredWidth(80);
        TBadminbuscarlib.getColumnModel().getColumn(5).setPreferredWidth(85);
        TBadminbuscarlib.getColumnModel().getColumn(6).setPreferredWidth(80);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTadminlibingidlib = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXTadmininglibtitu = new javax.swing.JTextField();
        TXTadmininglibpre = new javax.swing.JTextField();
        TXTadmininglibidautor = new javax.swing.JTextField();
        TXTadmininglibidedit = new javax.swing.JTextField();
        TXTadmininglibidgen = new javax.swing.JTextField();
        TXTadmininglibididio = new javax.swing.JTextField();
        BTNadmininglibing = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TXTadminactulibidlib = new javax.swing.JTextField();
        TXTadminactulibtitu = new javax.swing.JTextField();
        TXTadminactulibpre = new javax.swing.JTextField();
        TXTadminactulibidaut = new javax.swing.JTextField();
        TXTadminactulibidedit = new javax.swing.JTextField();
        TXTadminactulibidgen = new javax.swing.JTextField();
        TXTadminactulibididio = new javax.swing.JTextField();
        BTNadminactulibactu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBadminbuscarlib = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TXTadminbuscarlibidlib = new javax.swing.JTextField();
        BTNadminbuscalibbuscar = new javax.swing.JButton();
        BTNadminbuscarlibelim = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(187, 142, 211));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(640, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ID Libro: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Título: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Precio: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ID Autor: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("ID Editorial: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("ID Género: ");

        TXTadminlibingidlib.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminlibingidlib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminlibingidlib.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminlibingidlib.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("ID Idioma: ");

        TXTadmininglibtitu.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibtitu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibtitu.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibtitu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadmininglibpre.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibpre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibpre.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibpre.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadmininglibidautor.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibidautor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibidautor.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibidautor.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadmininglibidedit.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibidedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibidedit.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibidedit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadmininglibidgen.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibidgen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibidgen.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibidgen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadmininglibididio.setBackground(new java.awt.Color(204, 204, 204));
        TXTadmininglibididio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadmininglibididio.setForeground(new java.awt.Color(51, 51, 51));
        TXTadmininglibididio.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        BTNadmininglibing.setBackground(new java.awt.Color(178, 118, 211));
        BTNadmininglibing.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BTNadmininglibing.setForeground(new java.awt.Color(255, 255, 255));
        BTNadmininglibing.setText("Ingresar");
        BTNadmininglibing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNadmininglibingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTadmininglibidedit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TXTadmininglibidautor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(BTNadmininglibing, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTadminlibingidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadmininglibtitu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadmininglibpre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTadmininglibidgen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadmininglibididio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(TXTadmininglibidgen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadminlibingidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TXTadmininglibididio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TXTadmininglibtitu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TXTadmininglibpre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXTadmininglibidautor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTNadmininglibing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTadmininglibidedit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Libro", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(640, 380));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("ID Libro: ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Título: ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Precio: ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("ID Autor: ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("ID Editorial: ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("ID Idioma: ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("ID Género: ");

        TXTadminactulibidlib.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibidlib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibidlib.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibidlib.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibtitu.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibtitu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibtitu.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibtitu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibpre.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibpre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibpre.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibpre.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibidaut.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibidaut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibidaut.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibidaut.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibidedit.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibidedit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibidedit.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibidedit.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibidgen.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibidgen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibidgen.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibidgen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        TXTadminactulibididio.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminactulibididio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminactulibididio.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminactulibididio.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        BTNadminactulibactu.setBackground(new java.awt.Color(178, 118, 211));
        BTNadminactulibactu.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BTNadminactulibactu.setForeground(new java.awt.Color(255, 255, 255));
        BTNadminactulibactu.setText("Actualizar");
        BTNadminactulibactu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNadminactulibactuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTadminactulibpre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadminactulibtitu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTadminactulibidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTadminactulibidaut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TXTadminactulibidedit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXTadminactulibidgen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TXTadminactulibididio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(BTNadminactulibactu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TXTadminactulibidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(TXTadminactulibidgen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TXTadminactulibtitu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(TXTadminactulibididio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TXTadminactulibpre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TXTadminactulibidaut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(BTNadminactulibactu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TXTadminactulibidedit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Actualizar Libro", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TBadminbuscarlib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TBadminbuscarlib);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("ID Libro: ");

        TXTadminbuscarlibidlib.setBackground(new java.awt.Color(204, 204, 204));
        TXTadminbuscarlibidlib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TXTadminbuscarlibidlib.setForeground(new java.awt.Color(51, 51, 51));
        TXTadminbuscarlibidlib.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray));

        BTNadminbuscalibbuscar.setBackground(new java.awt.Color(178, 118, 211));
        BTNadminbuscalibbuscar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BTNadminbuscalibbuscar.setForeground(new java.awt.Color(255, 255, 255));
        BTNadminbuscalibbuscar.setText("Buscar");
        BTNadminbuscalibbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNadminbuscalibbuscarActionPerformed(evt);
            }
        });

        BTNadminbuscarlibelim.setBackground(new java.awt.Color(178, 118, 211));
        BTNadminbuscarlibelim.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        BTNadminbuscarlibelim.setForeground(new java.awt.Color(255, 255, 255));
        BTNadminbuscarlibelim.setText("Eliminar");
        BTNadminbuscarlibelim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNadminbuscarlibelimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTadminbuscarlibidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNadminbuscalibbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BTNadminbuscarlibelim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXTadminbuscarlibidlib, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNadminbuscalibbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNadminbuscarlibelim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buscar/Eliminar Libro", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNadmininglibingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNadmininglibingActionPerformed
        // TODO add your handling code here:
        String idlib= TXTadminlibingidlib.getText();
        String titu= TXTadmininglibtitu.getText();
        double pre= Double.parseDouble(TXTadmininglibpre.getText());
        String idaut= TXTadmininglibidautor.getText();
        String idedit= TXTadmininglibidedit.getText();
        String idgen= TXTadmininglibidgen.getText();
        String ididio= TXTadmininglibididio.getText();
        
        LibroDAO libdao= new LibroDAO();

        if (!idlib.isEmpty() && !titu.isEmpty() && !(pre == 0.0) && !idaut.isEmpty() && !idedit.isEmpty() && !idgen.isEmpty() && !ididio.isEmpty()) {
            Libro newbook= new Libro(idlib, titu, pre, idaut, idedit, idgen, ididio);
            
            try{
                libdao.guardar(newbook);
                JOptionPane.showMessageDialog(this, "Libro ingresado con éxito", "Felicidades Shinji", JOptionPane.INFORMATION_MESSAGE);                                                            
            }catch(SQLException goliat){//problemas con la BD
                JOptionPane.showMessageDialog(this, "Error al ingresar el Libro" + goliat.getMessage(), "Fue", JOptionPane.ERROR_MESSAGE); 
                logger.log(Level.SEVERE, "Error al ingresar los datos del inventario", goliat); // Loguear el error para depuración
                goliat.printStackTrace();           
            }            
            }else{
                JOptionPane.showMessageDialog(this, "Rellenar todos los campos", "Información Incompleta", JOptionPane.INFORMATION_MESSAGE);
           
            }
        TXTadminlibingidlib.setText("");
        TXTadmininglibtitu.setText("");
        TXTadmininglibpre.setText("");
        TXTadmininglibidautor.setText("");
        TXTadmininglibidedit.setText("");
        TXTadmininglibidgen.setText("");
        TXTadmininglibididio.setText("");
    }//GEN-LAST:event_BTNadmininglibingActionPerformed

    private void BTNadminactulibactuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNadminactulibactuActionPerformed
        // TODO add your handling code here:
        String idlib= TXTadminactulibidlib.getText();
        String titu= TXTadminactulibtitu.getText();
        double pre= Double.parseDouble(TXTadminactulibpre.getText());
        String idaut= TXTadminactulibidaut.getText();
        String idedit= TXTadminactulibidedit.getText();
        String idgen= TXTadminactulibidgen.getText();
        String ididio= TXTadminactulibididio.getText();
        
        LibroDAO libdao= new LibroDAO();
        
        if (!idlib.isEmpty() && !titu.isEmpty() && !(pre == 0.0) && !idaut.isEmpty() && !idedit.isEmpty() && !idgen.isEmpty() && !ididio.isEmpty()) {
            try{
                Libro libactu= libdao.obtenerPorId(idlib);//guardar en objeto Libro
                libactu.setTitulo(titu);
                libactu.setPrecio(pre);
                libactu.setIdAutor(idaut);
                libactu.setIdEdito(idedit);
                libactu.setIdGen(idgen);
                libactu.setIdIdioma(ididio);

                libdao.actualizar(libactu);
                JOptionPane.showMessageDialog(this, "Libro actuaizado con éxito", "Felicidades Shinji", JOptionPane.INFORMATION_MESSAGE);                                                                     
            }catch(SQLException ahri){
                JOptionPane.showMessageDialog(this, "Error al actualizar el Libro" + ahri.getMessage(), "Fue", JOptionPane.ERROR_MESSAGE); 
                logger.log(Level.SEVERE, "Error al actualizar los datos del inventario", ahri); // Loguear el error para depuración
                ahri.printStackTrace(); 
            }
        }else{
            JOptionPane.showMessageDialog(this, "Rellenar todos los campos", "Información Incompleta", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_BTNadminactulibactuActionPerformed

    private void BTNadminbuscalibbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNadminbuscalibbuscarActionPerformed
        // TODO add your handling code here:
        String idlib= TXTadminbuscarlibidlib.getText();
        LibroDAO libdao= new LibroDAO();
        AutorDAO autdao= new AutorDAO();
        EditorialDAO editdao= new EditorialDAO();
        GeneroDAO gendao= new GeneroDAO();
        IdiomaDAO ididao= new IdiomaDAO();
        
        m.setRowCount(0);       
        
        try{      
            if (!idlib.isEmpty()) {//si hay algo en el textfield
                Libro libbuscado= libdao.obtenerPorId(idlib);
                if (libbuscado != null) {
                    Libro lib= libdao.obtenerPorId(idlib);
                    Autor aut= autdao.obtenerPorId(lib.getIdAutor());//sacar el id del campo del objeto lib creado
                    Editorial edit= editdao.obtenerPorId(lib.getIdEdito());
                    Genero gen= gendao.obtenerPorId(lib.getIdGen());
                    Idioma idi= ididao.obtenerPorId(lib.getIdIdioma());
                  
                    Object[] libdatos= {libbuscado.getIdLibro(), libbuscado.getTitulo(), libbuscado.getPrecio(), 
                    aut.getNomAutor(), edit.getNomEdito(), gen.getGenero(), idi.getIdioma()};
                    
                    m.addRow(libdatos);
                }else{
                    JOptionPane.showMessageDialog(this, "No se encontro el Libro o No Existe", "Por favor no", JOptionPane.WARNING_MESSAGE);
                }
            }else{//si no hay nada en el textfield
                List <Libro> allbooks= libdao.obtenerTodos();
                
                for(Libro libro: allbooks ){                   
                    Autor aut= autdao.obtenerPorId(libro.getIdAutor());
                    Editorial edit= editdao.obtenerPorId(libro.getIdEdito());
                    Genero gen= gendao.obtenerPorId(libro.getIdGen());
                    Idioma idi= ididao.obtenerPorId(libro.getIdIdioma());
                  
                    Object[] libdatos= {libro.getIdLibro(), libro.getTitulo(), libro.getPrecio(), 
                    aut.getNomAutor(), edit.getNomEdito(), gen.getGenero(), idi.getIdioma()};
                    
                    m.addRow(libdatos);                    
                }
            }
        }catch(SQLException besosalaire){
            JOptionPane.showMessageDialog(this, "Problemas con la BD" + besosalaire.getMessage(), "Por favor no", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al obtener los datos del inventario", besosalaire); // Loguear el error para depuración
            besosalaire.printStackTrace(); 
        }
        TXTadminbuscarlibidlib.setText(""); 
    }//GEN-LAST:event_BTNadminbuscalibbuscarActionPerformed

    private void BTNadminbuscarlibelimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNadminbuscarlibelimActionPerformed
        // TODO add your handling code here:
        int fila= TBadminbuscarlib.getSelectedRow();
        String idlibelim= TBadminbuscarlib.getModel().getValueAt(fila, 0).toString();
        
        LibroDAO libdao= new LibroDAO();
        
        try{
            int confirm= JOptionPane.showConfirmDialog(this, "Confirmar Eliminación de Libro: "+ idlibelim, "Confirmación", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                libdao.eliminar(idlibelim);
                JOptionPane.showMessageDialog(this, "Libro eliminado con éxito", "Felicidades Shinji", JOptionPane.INFORMATION_MESSAGE);                              
            }else{
                JOptionPane.showMessageDialog(this, "Eliminación Cancelada", "Felicidades Shinji", JOptionPane.INFORMATION_MESSAGE);                                             
            }         
        }catch(SQLException blueheart){
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el Libro debido a problemas con la BD" + blueheart.getMessage(), "Por favor no", JOptionPane.ERROR_MESSAGE);
            logger.log(Level.SEVERE, "Error al eliminar los datos del inventario", blueheart); // Loguear el error para depuración

            blueheart.printStackTrace();            
        }
        TXTadminbuscarlibidlib.setText("");                
    }//GEN-LAST:event_BTNadminbuscarlibelimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNadminactulibactu;
    private javax.swing.JButton BTNadminbuscalibbuscar;
    private javax.swing.JButton BTNadminbuscarlibelim;
    private javax.swing.JButton BTNadmininglibing;
    private javax.swing.JTable TBadminbuscarlib;
    private javax.swing.JTextField TXTadminactulibidaut;
    private javax.swing.JTextField TXTadminactulibidedit;
    private javax.swing.JTextField TXTadminactulibidgen;
    private javax.swing.JTextField TXTadminactulibididio;
    private javax.swing.JTextField TXTadminactulibidlib;
    private javax.swing.JTextField TXTadminactulibpre;
    private javax.swing.JTextField TXTadminactulibtitu;
    private javax.swing.JTextField TXTadminbuscarlibidlib;
    private javax.swing.JTextField TXTadmininglibidautor;
    private javax.swing.JTextField TXTadmininglibidedit;
    private javax.swing.JTextField TXTadmininglibidgen;
    private javax.swing.JTextField TXTadmininglibididio;
    private javax.swing.JTextField TXTadmininglibpre;
    private javax.swing.JTextField TXTadmininglibtitu;
    private javax.swing.JTextField TXTadminlibingidlib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
