/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import DAO.AutorDAO;
import DAO.EditorialDAO;
import DAO.GeneroDAO;
import DAO.IdiomaDAO;
import DAO.LibroDAO;
import Model.Autor;
import Model.Editorial;
import Model.Genero;
import Model.Idioma;
import Model.Libro;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class caja_ventas extends javax.swing.JPanel {
    DefaultTableModel m = new DefaultTableModel();
    public caja_ventas() {
        initComponents();
        mostrarCabecera();
    }
    
    public void mostrarCabecera(){
        m.addColumn("id");
        m.addColumn("Titulo");
        m.addColumn("Precio");
        m.addColumn("Autor");
        m.addColumn("Editorial");
        m.addColumn("Genero");
        m.addColumn("Idioma");
        tblLibros.setModel(m);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCliente = new javax.swing.JTabbedPane();
        pnlListarLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        pnlRegistroVentaCli = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtDni1 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        pnlRegistroVentasSinCli = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtDni3 = new javax.swing.JTextField();
        btnVenderSinCli = new javax.swing.JButton();
        btnAddSinCli = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlCliente.setBackground(new java.awt.Color(187, 142, 211));
        pnlCliente.setForeground(new java.awt.Color(255, 255, 255));

        pnlListarLibros.setBackground(new java.awt.Color(255, 255, 255));

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        btnListar.setBackground(new java.awt.Color(187, 142, 211));
        btnListar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar Libros");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListarLibrosLayout = new javax.swing.GroupLayout(pnlListarLibros);
        pnlListarLibros.setLayout(pnlListarLibrosLayout);
        pnlListarLibrosLayout.setHorizontalGroup(
            pnlListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarLibrosLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        pnlListarLibrosLayout.setVerticalGroup(
            pnlListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarLibrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pnlCliente.addTab("Listar Libros", pnlListarLibros);

        pnlRegistroVentaCli.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("DNI del cliente:");

        txtDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel16.setFont(new java.awt.Font("Eras Bold ITC", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Codigo del libro:");

        txtDni1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAdd.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnAdd.setText("Añadir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnVender.setBackground(new java.awt.Color(187, 142, 211));
        btnVender.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroVentaCliLayout = new javax.swing.GroupLayout(pnlRegistroVentaCli);
        pnlRegistroVentaCli.setLayout(pnlRegistroVentaCliLayout);
        pnlRegistroVentaCliLayout.setHorizontalGroup(
            pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroVentaCliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroVentaCliLayout.createSequentialGroup()
                        .addGroup(pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroVentaCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );

        pnlRegistroVentaCliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16});

        pnlRegistroVentaCliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDni, txtDni1});

        pnlRegistroVentaCliLayout.setVerticalGroup(
            pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroVentaCliLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlRegistroVentaCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDni1)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVender)
                .addGap(17, 17, 17))
        );

        pnlCliente.addTab("Registrar Ventas con Cliente", pnlRegistroVentaCli);

        pnlRegistroVentasSinCli.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel18.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Codigo del libro:");

        txtDni3.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N

        btnVenderSinCli.setBackground(new java.awt.Color(187, 142, 211));
        btnVenderSinCli.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnVenderSinCli.setForeground(new java.awt.Color(255, 255, 255));
        btnVenderSinCli.setText("Vender");
        btnVenderSinCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderSinCliActionPerformed(evt);
            }
        });

        btnAddSinCli.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnAddSinCli.setText("Añadir");
        btnAddSinCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSinCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroVentasSinCliLayout = new javax.swing.GroupLayout(pnlRegistroVentasSinCli);
        pnlRegistroVentasSinCli.setLayout(pnlRegistroVentasSinCliLayout);
        pnlRegistroVentasSinCliLayout.setHorizontalGroup(
            pnlRegistroVentasSinCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroVentasSinCliLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtDni3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddSinCli)
                .addGap(34, 34, 34))
            .addGroup(pnlRegistroVentasSinCliLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroVentasSinCliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVenderSinCli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        pnlRegistroVentasSinCliLayout.setVerticalGroup(
            pnlRegistroVentasSinCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroVentasSinCliLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlRegistroVentasSinCliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDni3)
                    .addComponent(btnAddSinCli))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVenderSinCli)
                .addGap(20, 20, 20))
        );

        pnlCliente.addTab("Registrar Ventas sin Cliente", pnlRegistroVentasSinCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCliente)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            LibroDAO ld = new LibroDAO();
            List<Libro> vl = ld.obtenerTodos();
            IdiomaDAO idd = new IdiomaDAO();
            GeneroDAO gd = new GeneroDAO();
            AutorDAO ad = new AutorDAO();
            EditorialDAO ed = new EditorialDAO();
            m.setRowCount(0); 
            for(Libro libro: vl){
                Idioma idioma = idd.obtenerPorId(libro.getIdIdioma());
                Genero genero = gd.obtenerPorId(libro.getIdGen());
                Autor autor = ad.obtenerPorId(libro.getIdAutor());
                Editorial editorial = ed.obtenerPorId(libro.getIdEdito());
                
                Object[] data = {
                    libro.getIdLibro(),
                    libro.getTitulo(),
                    libro.getPrecio(),
                    autor.getNomAutor()+" "+autor.getApeAutor(),
                    editorial.getNomEdito(),
                    genero.getGenero(),
                    idioma.getIdioma(),
                };
                m.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al obtener datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnAddSinCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSinCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSinCliActionPerformed

    private void btnVenderSinCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderSinCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVenderSinCliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddSinCli;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVenderSinCli;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTabbedPane pnlCliente;
    private javax.swing.JPanel pnlListarLibros;
    private javax.swing.JPanel pnlRegistroVentaCli;
    private javax.swing.JPanel pnlRegistroVentasSinCli;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtDni1;
    private javax.swing.JTextField txtDni3;
    // End of variables declaration//GEN-END:variables
}
