/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author Charisse Livia
 */
public class Cajero extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    public Cajero() {
        initComponents();
                Color customColor = new Color(255,204,153); 
        getContentPane().setBackground(customColor);  
        
        caja_vender vender = new caja_vender();
        vender.setVisible(false); // Inicialmente oculto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelcajero = new javax.swing.JPanel();
        vender = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        libros = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        stock = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 153));
        setMinimumSize(new java.awt.Dimension(1000, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelcajero.setBackground(new java.awt.Color(255, 255, 255));
        panelcajero.setMinimumSize(new java.awt.Dimension(800, 471));

        javax.swing.GroupLayout panelcajeroLayout = new javax.swing.GroupLayout(panelcajero);
        panelcajero.setLayout(panelcajeroLayout);
        panelcajeroLayout.setHorizontalGroup(
            panelcajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelcajeroLayout.setVerticalGroup(
            panelcajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        getContentPane().add(panelcajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 149, 800, -1));

        vender.setBackground(new java.awt.Color(255, 204, 153));
        vender.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        vender.setForeground(new java.awt.Color(255, 255, 255));
        vender.setText("Vender");
        vender.setBorder(null);
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });
        getContentPane().add(vender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 70));

        jSeparator2.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator2.setForeground(new java.awt.Color(255, 204, 153));
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 90));

        libros.setBackground(new java.awt.Color(255, 204, 153));
        libros.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        libros.setForeground(new java.awt.Color(255, 255, 255));
        libros.setText("Clientes");
        libros.setBorder(null);
        getContentPane().add(libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 180, 70));

        jSeparator4.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator4.setForeground(new java.awt.Color(255, 204, 153));
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, 90));

        stock.setBackground(new java.awt.Color(255, 204, 153));
        stock.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setText("Consultas");
        stock.setBorder(null);
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 180, 70));

        jSeparator5.setBackground(new java.awt.Color(255, 204, 153));
        jSeparator5.setForeground(new java.awt.Color(255, 204, 153));
        jSeparator5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 4));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, 90));

        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel6.setText("¡Bienvenido querido cajero!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel8.setText("SISTEMA DE CAJA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed

        panelcajero.setVisible(false); // Oculta el panel principal
        vender.setVisible(true); 
    }//GEN-LAST:event_venderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton libros;
    private javax.swing.JPanel panelcajero;
    private javax.swing.JButton stock;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables
}
